config/routes.rb
Rails.application.routes.draw do

  root 'tasks#new'

  get 'tasks/assign_task', to: 'tasks#assign_task'
  get 'tasks/cancel_task', to: 'tasks#cancel_task'
  get 'tasks/choose_location', to: 'tasks#choose_location'
  get 'tasks/request_uber', to: 'tasks#request_uber'
  get 'tasks/confirm_uber', to: 'tasks#confirm_uber'
  get 'tasks/show_ride', to: 'tasks#show_ride'

  resources :tasks
  resources :assistants
end

app/models/assistant.rb
class Assistant < ActiveRecord::Base

  has_many :tasks

  validates :full_name, :email, :phone, presence: true

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :assistant

  validates :full_name, :email, :phone, :title, :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assistants_controller.rb
class AssistantsController < ApplicationController

  def show
    @assistant = Assistant.find_by(assistant_params)
  end

  def new
    @assistant = Assistant.new
  end

  def create
    @assistant = Assistant.new(assistant_params)
    if @assistant.save
      flash[:notice] = 'Thank you for signing up as an assistant. You can now choose a task.'
      redirect_to tasks_path
    else
      flash[:danger] = "Your registration didn't get through, please fill in all fields."
      render action: "new"
    end
  end

  private

  def assistant_params
    params.require(:assistant).permit(:full_name, :email, :phone)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :get_uber_client

  def index
    @tasks = Task.all
    @user = @client.me
  end

  def show
    @task = Task.find_by(task_params)
  end

  def new
    @task = Task.new
  end

  def create
    @user = @client.me
    @task = Task.new(task_params)
    @task.full_name = "#{@user.first_name} #{@user.last_name}"
    @task.email = @user.email
    @task.phone = '081223040'
    if @task.save
      flash[:notice] = 'Thank you for adding a task.'
      redirect_to tasks_path
    else
      flash[:notice] = 'Your task could not be added.'
      redirect_to root_path
      # TODO: client side validation?
    end
  end

  def assign_task
    @assistant = Assistant.first #TODO: get the current logged in assistant
    @task = Task.find(params[:id])
    @task.available = false
    @task.assistant_id = @assistant.id
    if @task.save
      flash[:success] = "This task an now only be completed by you."
      redirect_to tasks_path
    else
      flash[:danger] = "You didn't pick the task up successfully. Try again."
      redirect_to tasks_path
    end
  end

  def cancel_task
    @task = Task.find(params[:id])
    @task.available = true
    @task.assistant_id = nil
    if @task.save
      flash[:success] = "The task is now available to others again."
      redirect_to tasks_path
    else
      flash[:danger] = "You still need to complete this task."
      redirect_to tasks_path
    end
  end

  def choose_location
    render 'choose_location'
  end

  def request_uber
    # without product_id the trip_request will automatically find the cheapest car
    request = @client.trip_request(start_latitude: params[:start_lat], start_longitude: params[:start_lng],
      end_latitude: params[:end_lat], end_longitude: params[:end_lng])
    request_id = request.request_id
    # @client.products(latitude: params[:start_lat], longitude: params[:start_lng])
    @client.trip_update(request_id, 'accepted')
    details = @client.trip_details(request_id)
    @driver = details.driver
    if details.driver
      flash[:success] = "Your Uber will arrive at your location shortly. Your driver is #{@driver.name}, and can be reached at #{@driver.phone_number}"
      redirect_to tasks_show_ride_path
    else
      flash[:success] = "Something went wrong, please try again."
      redirect_to tasks_choose_location_path
    end
  end

  private

  def task_params
    params.require(:task).permit(:id, :full_name, :email, :phone, :title, :description, :money)
  end

  def get_uber_client
    # Get your credentials from the uber API docs: https://developer.uber.com/docs/authentication
    @client = Uber::Client.new do |config|
      config.server_token  = [your_server_token]
      config.client_id = [your_client_id]
      config.client_secret = [your_client_secret]
      config.bearer_token  = [your_bearer_token]
      config.sandbox = true
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_user

  def index
    # overview of all assistants
  end

  def show
    @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  private

  def set_user
    @user = Uber::Client.new do |config|
      config.server_token  = "uHf5yHFbjoE11qRnJW8pN8S98EX79hUc_xXPS4iW"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistants_helper.rb
module AssistantsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assistants/new.html.erb
 <header class="mainheader">
  <div class="container sm-pt-1 sm-pb-1">
    <h1 class="h3">Instant Assistant</h1>
    <nav class="mainheader__nav">
      <ul>
        <li><%= link_to "Create a task", root_path %></li>
        <li><%= link_to "Show me tasks", tasks_path %></li>
        <li><%= link_to "Assistant", new_assistant_path, class: 'active' %></li>
      </ul>
    </nav>
  </div>
</header>

<main class="container sm-pt-1 sm-pb-1 lg-pt-2 lg-pb-2">
  <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
  <% end -%>

  <%= form_for @assistant do |f| %>My name is
  <%= f.text_field :full_name , :placeholder => 'e.g. Coconut Water', 'data-subline' => 'Full name'%>, &amp; email is <%= f.text_field :email , :placeholder => 'name@mail.com' , 'data-subline' => 'Valid email' %>, you can reach me at
    <%= f.text_field :phone , :placeholder => '0031621977967' , 'data-subline' => 'e.g 0031 6 21 97 7967' %>

    <div class="nl-submit-wrap">

      <%= button_to @assistant, :class => 'nl-submit' do %>
        Start helping
      <% end %>

    </div>

    <div class="nl-overlay"></div>

  <% end %>
</main>

<script>
  var nlform = new NLForm( document.getElementById( 'new_assistant' ) );
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta charset="utf-8">
  <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">

  <title>InstantAssistant</title>

  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700|Merriweather:400,400italic,700,700italic,300,300italic' rel='stylesheet' type='text/css'>
  <!-- <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> -->
  <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/choose_location.html.erb
<fieldset class='gllpLatlonPicker'>
	<div class="locationform">
		<span class="location-start">Where are you now?</span> <span class="location-end">Where do you wanna go?</span> <input type="text" class="gllpSearchField" value="Machinegebouw, Pazzanistraat 8, Amsterdam">
		<div style="display:none;">
			lat/lon:
			<input type="text" class="gllpLatitude" value="52.3702157"/>
			<input type="text" class="gllpLongitude" value="4.895167899999933"/>
			zoom: <input type="text" class="gllpZoom" value="15"/>
		</div>
		<button class="button button--darken gllpSearchButton gllpSearchButtonFrom"><i class="fa fa-check-circle" aria-hidden="true"></i>Get pickup location</button>
		<button class="button button--darken gllpSearchButtonTo hide"><i class="fa fa-check-circle" aria-hidden="true"></i>Get Dropoff location</button>

		<a href="" class="button button--small refresh"><i class="fa fa-refresh" aria-hidden="true"></i> Refresh requests</a>

		<p class="xtart hide">Your current location is: <br><span class="getStartlocation"></span></p>
		<p class="xend hide">Your end point is: <br><span class="getEndlocation"></span></p>

		<div class="requber hide">
			<a href="" class="confirmlocation button button--small"><i class="fa fa-map-marker" aria-hidden="true"></i>Confirm locations</a>
			<%= link_to "Request UBER", {controller: 'tasks' ,action: 'request_uber', start_lat: '52.3702157', start_lng: '4.895167899999933', end_lat: '4.895167899999933', end_lng: '77.20902120000005'}, class: 'button button--small ubercall hide' %>
					</div>

	</div>
	<div id="map" class="gllpMap"></div>
</fieldset>

<div class="nl-overlay">
  <div class="spinner hide">
    <div class="double-bounce1"></div>
    <div class="double-bounce2"></div>
  </div>
</div>

<%= link_to "Confirm UBER for", {controller: 'tasks' ,action: 'confirm_uber'}, class: 'button button--small' %>

app/views/tasks/index.html.erb
 <header class="mainheader">
  <div class="container sm-pt-1 sm-pb-1">
    <h1 class="h3">Instant Assistant</h1>
    <nav class="mainheader__nav">
      <ul>
        <li><%= link_to "Create a task", root_path %></li>
        <li><%= link_to "Show me tasks", tasks_path, :class => 'active' %></li>
        <li><%= link_to "Sign up", new_assistant_path %></li>
      </ul>
    </nav>
  </div>
</header>

<main class="container sm-pt-1 sm-pb-1 md-pt-2 md-pb-2">
  <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
  <% end -%>

  <ul class="tasks">
    <% @tasks.order(available: :desc).each do |t| %>
    <li class="task <%= 'taken' if t.available == false %>">
      <h2><%= t.title %></h2>
      <p><%= t.description %></p>
      <div class="actions">
        <% if t.available == true %>
          <p class="est">You'll earn:&euro; <%= t.money %></p>
          <%= link_to "Pick this task", {controller: 'tasks', action: 'assign_task', id: t.id}, class: 'button button--small', 'data-push-notification' => t.money, 'data-push-notification-title' => t.title %>
        <% else %>
        <div class="checkblock">
          <%= t.assistant.full_name.split(' ').first %> is taking care of it <br>at
          <time><%= t.updated_at.strftime("%d %B %Y %H:%M") %></time>

          <div class="nextactions">
            <%= link_to "UBER", 'tasks/choose_location', class: 'button button--small' %>
            <%= link_to "Cancel", { controllers: 'tasks', action: "cancel_task", id: t.id }, 'data-push-notification-cancel' => '', 'data-push-notification-title' => t.title, class: 'button button--small button--cancel' %>
          </div>

          <%= link_to "Cancel", { action: "cancel_task", id: t.id }, 'data-push-notification-cancel' => '', 'data-push-notification-title' => t.title, class: 'button button--small button--cancel' %>

        </div>
        <% end %>
      </div>
    </li>
    <% end %>

    <li class="task expired">
      <h2>do all my groceries for the next year</h2>
      <p>This is just a dummy description</p>
      <div class="actions">
        <p class="est">You could've earned:&euro; 50</p>
        <a href="" class="button button--small">Expired</a>
      </div>
    </li>
  </ul>
</main>

app/views/tasks/new.html.erb
 <header class="mainheader">
  <div class="container sm-pt-1 sm-pb-1">
    <h1 class="h3">Instant Assistant</h1>
    <nav class="mainheader__nav">
      <ul>
        <li><%= link_to "Create a task", root_path, class: 'active' %></li>
        <li><%= link_to "Show me tasks", tasks_path %></li>
        <li><%= link_to "Sign up", new_assistant_path %></li>
      </ul>
    </nav>
  </div>
</header>

<main class="container sm-pt-1 sm-pb-1 lg-pt-2 lg-pb-2">
  <%= form_for @task do |f| %>I'm looking for someone who can help me

    <%= f.text_field :title , :placeholder => 'be awesome', 'data-subline' => 'For example: be awesome' %>

    with description of

    <%= f.text_field :description , :placeholder => 'cleaning my mess', 'data-subline' => 'For example: cleaning my mess' %>

    for €<%= f.number_field :money , :placeholder => '25', 'data-subline' => 'e.g. €50' %>

    <div class="nl-submit-wrap">

      <%= button_to @task, :class => 'nl-submit' do %>
        Create
      <% end %>

    </div>

    <div class="nl-overlay">
      <div class="spinner hide">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
      </div>
    </div>

  <% end %>

</main>

<script>
  var nlform = new NLForm( document.getElementById( 'new_task' ) );
</script>

app/views/tasks/show_ride.html.erb
 <header class="mainheader showrideheader">
  <div class="container sm-pt-1 sm-pb-1">
    <h1 class="h3">Instant Assistant</h1>
    <nav class="mainheader__nav">
      <ul>
        <li><%= link_to "Create a task", root_path %></li>
        <li><%= link_to "Show me tasks", tasks_path %></li>
        <li><%= link_to "Sign up", new_assistant_path %></li>
      </ul>
    </nav>
  </div>
</header>

<main class="container sm-pt-1 sm-pb-1 md-pt-2 md-pb-2">
  <% flash.each do |name, msg| -%>
  <h4><%= content_tag :div, msg, class: name, style: 'color: white' %><h4>
  <% end -%>
  <div id="maprd"></div>
  <div class="driver">
    <div class="john">
      <%= image_tag('john.jpg', size:'80x80') %>
    </div>
    <span class="name">John</span>
    <span class="phone"><i class="fa fa-phone" aria-hidden="true"></i>(555)555-5555</span>
  </div>
  <div class="for-future-banner">
    <h3>On this map you can follow the Uber car.</h3>
  </div>
</main>

<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('maprd'), {
      center: {lat: 52.3863436, lng: 4.87281669999993},
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      scrollwheel: false,
      mapTypeControl: false,
      disableDoubleClickZoom: true,
      zoomControlOptions: true,
      streetViewControl: false
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDvi-Zm2zjuPQloKoy-JqDu1iQJKKz-TAQ&callback=initMap"
async defer></script>